name: ApexCE
main: ApexCE\Main
version: 1.0.0
api: 5.0.0
author: ApexPELegitz
description: Custom Enchants Plugin (Driller, TreeDestroyer, Lifesteal, Lightning)

commands:
  ce:
    description: Custom Enchant main command
    usage: "/ce give <player> <enchant> <level> | /ce givebook <player> <enchant> <level>"
    permission: apexce.use

permissions:
  apexce.use:
    default: true
